[package]
name = "s2_geocoder"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
s2 = "0.0.10"
ahash = "0.7.6"
croaring = "0.5.1"
kdbush = "0.2.0"